### PR TITLE
ppc64le docker slaves

### PR DESCRIPTION
**Pull request by ramereth**
This is needed for getting our POWERCI infrastructure up.

### CODE REVIEW

**Comment by ramereth** [comment]
[POWER CI: Update hardcoded paths to work with current infra](https://trello.com/c/e0BctJxL/541-power-ci-update-hardcoded-paths-to-work-with-current-infra)

**Comment by Codysseus** [comment]
How should I test this? Some of these images are not on dockerhub.

**Comment by ramereth** [comment]
There really isn't an easy way to test this unfortunately. Which images are not on dockerhub?

**Comment by Codysseus** [comment]
I only could not find `ppc64le/centos`.

**Pull request merged**
